import 'constants.dart';

class Animal {
  final String name;
  final String breedline1;
  final String breedline2;
  final String gender;
  final String image;
  final String location;
  final String ageNumber;
  final String ageUnit;
  final String weightNumber;
  final String weightUnit;
  final String ownerImagePath;
  final String ownerName;
  final String ownerCategory;
  final String ownerStatement;
  final List<String> photos;
  final String breed;
  final String id;
  final String email;
  bool isFavourite;
  bool isAdopted;
  Animal(
      {this.name,
      this.breedline1,
      this.breedline2,
      this.ageNumber,
      this.ageUnit,
      this.gender,
      this.image,
      this.location,
      this.weightNumber,
      this.weightUnit,
      this.ownerCategory,
      this.ownerName,
      this.ownerImagePath,
      this.ownerStatement,
      this.photos,
      this.breed,
      this.id,
      this.isFavourite = false,
      this.email,
      this.isAdopted = false});

  void toggleFavourite() {
    isFavourite = !isFavourite;
  }

  void toggleAdopted() {
    isAdopted = !isAdopted;
  }
}

List<Animal> dogs = [
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '0',
    name: 'Chilli',
    breedline1: 'Cocker',
    breedline2: 'Spaniel',
    breed: 'Cocker Spaniel',
    ageNumber: '1',
    ageUnit: "year",
    gender: 'Female',
    image: 'images/chilli1.jpeg',
    location: 'New Delhi\, India',
    weightNumber: '11',
    weightUnit: 'kg',
    ownerName: 'Michael Scott',
    ownerImagePath: 'images/ishaan.png',
    ownerCategory: 'Owner',
    ownerStatement: kIshaanText,
    photos: ['images/chilli1.jpeg', 'images/chilli2.png', 'images/chilli3.png'],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '1',
    name: 'Moose',
    breedline1: 'Corgi',
    breedline2: '',
    breed: 'Corgi',
    ageNumber: '5',
    ageUnit: "years",
    gender: 'Male',
    image: 'images/moose1.png',
    location: 'Mumbai\, India',
    weightNumber: '13',
    weightUnit: 'kg',
    ownerName: 'Pam',
    ownerImagePath: 'images/srishti.jpg',
    ownerCategory: 'Owner',
    ownerStatement: kMooseText,
    photos: [
      'images/moose1.png',
      'images/moose2.png',
      'images/moose3.png',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '2',
    name: 'Kyra',
    breedline1: 'Dach-',
    breedline2: 'shund',
    breed: 'Dachshund',
    ageNumber: '4',
    ageUnit: 'years',
    gender: 'Female',
    image: 'images/kyra1.png',
    location: 'New Delhi\, India',
    weightNumber: '7',
    weightUnit: 'kg',
    ownerName: 'Jim Halpert',
    ownerImagePath: 'images/laasya.png',
    ownerCategory: 'Owner',
    ownerStatement: kKyraStatement,
    photos: [
      'images/kyra1.png',
      'images/kyra2.png',
      'images/kyra3.png',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '3',
    name: 'Marshall',
    breedline1: 'Golden',
    breedline2: 'Retriever',
    breed: 'Golden Retriever',
    ageNumber: '3',
    ageUnit: 'years',
    gender: 'Male',
    image: 'images/marshall1.png',
    location: 'New Delhi\, India',
    weightNumber: '30',
    weightUnit: 'kg',
    ownerName: 'Animal Care Center',
    ownerImagePath: 'images/shelter1.png',
    ownerCategory: 'Shelter',
    ownerStatement: kMarshallText,
    photos: [
      'images/marshall1.png',
      'images/marshall2.png',
      'images/marshall3.png',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '4',
    name: 'Soba',
    breedline1: 'Toy',
    breedline2: 'Poodle',
    breed: 'Toy Poodle',
    ageNumber: '2',
    ageUnit: 'years',
    gender: 'Female',
    image: 'images/soba1.png',
    location: 'New Delhi\, India',
    weightNumber: '4',
    weightUnit: 'kg',
    ownerName: 'Dogs Association',
    ownerImagePath: 'images/bhavini.png',
    ownerCategory: 'Owner',
    ownerStatement: kSobaText,
    photos: [
      'images/soba1.png',
      'images/soba2.png',
      'images/soba3.png',
    ],
  ),
];

List<Animal> cats = [
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '5',
    name: 'Buffy',
    breedline1: 'British',
    breedline2: ' short\n haired',
    breed: 'British short-haired',
    ageNumber: '4',
    ageUnit: 'years',
    gender: 'Female',
    image: 'images/buffy1.jpg',
    location: 'New Delhi\, India',
    weightNumber: '4',
    weightUnit: 'kg',
    ownerName: 'Dwight Shroot',
    ownerImagePath: 'images/nehal.png',
    ownerCategory: 'Owner',
    ownerStatement: kBuffySeolText,
    photos: [
      'images/buffy1.jpg',
      'images/buffy2.jpeg',
      'images/buffy3.png',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '6',
    name: 'Willow',
    breedline1: 'British',
    breedline2: ' short\n haired',
    breed: 'British short-haired',
    ageNumber: '8',
    ageUnit: 'mos.',
    gender: 'Female',
    image: 'images/willow1.png',
    location: 'New Delhi\, India',
    weightNumber: '3',
    weightUnit: 'kg',
    ownerName: 'Chetan Anand',
    ownerImagePath: 'images/mansi.jpg',
    ownerCategory: 'Owner',
    ownerStatement: kWillowText,
    photos: [
      'images/willow1.png',
      'images/willow2.png',
      'images/willow3.png',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '7',
    name: 'Buttons',
    breedline1: 'Exotic',
    breedline2: ' short\n haired',
    breed: 'Exotic short-haired',
    ageNumber: '1',
    ageUnit: 'year',
    gender: 'Male',
    image: 'images/buttons1.png',
    location: 'New Delhi\, India',
    weightNumber: '5',
    weightUnit: 'kg',
    ownerName: 'Rishabh Mittal',
    ownerImagePath: 'images/manasvi.JPG',
    ownerCategory: 'Owner',
    ownerStatement: kButtonsText,
    photos: [
      'images/buttons1.png',
      'images/buttons2.png',
      'images/buttons3.png',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '8',
    name: 'Seol',
    breedline1: 'Sphynx',
    breedline2: '',
    breed: 'Sphynx',
    ageNumber: '2',
    ageUnit: 'years',
    gender: 'Female',
    image: 'images/seol1.png',
    location: 'New Delhi\, India',
    weightNumber: '3',
    weightUnit: 'kg',
    ownerName: 'Friendicoes',
    ownerImagePath: 'images/shelter3.jpg',
    ownerCategory: 'Shelter',
    ownerStatement: kBuffySeolText,
    photos: [
      'images/seol1.png',
      'images/seol2.png',
      'images/seol3.png',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '9',
    name: 'Rex',
    breedline1: 'Scottish',
    breedline2: 'Fold',
    breed: 'Scottish Fold',
    ageNumber: '6',
    ageUnit: 'years',
    gender: 'Male',
    image: 'images/rex1.png',
    location: 'New Delhi\, India',
    weightNumber: "4",
    weightUnit: 'kg',
    ownerName: 'Kashish',
    ownerImagePath: 'images/sameeha.png',
    ownerCategory: 'Owner',
    ownerStatement: kRexText,
    photos: [
      'images/rex1.png',
      'images/rex2.png',
      'images/rex3.png',
    ],
  ),
];

List<Animal> bunnies = [
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '10',
    name: 'Miso',
    breedline1: 'Holland',
    breedline2: 'Lop',
    breed: 'Holland Lop',
    ageNumber: '7',
    ageUnit: 'years',
    gender: 'Male',
    image: 'images/miso1.png',
    location: 'New Delhi\, India',
    weightNumber: '1.5',
    weightUnit: 'kg',
    ownerName: 'Mansi Aggarwal',
    ownerImagePath: 'images/ayush.png',
    ownerCategory: 'Owner',
    ownerStatement: kMisoText,
    photos: [
      'images/miso1.png',
      'images/miso2.png',
      'images/miso3.png',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '11',
    name: 'PuiPui',
    breedline1: ' Nether-',
    breedline2: 'land\nDwarf',
    breed: 'Netherland Dwarf',
    ageNumber: '2',
    ageUnit: 'years',
    gender: 'Female',
    image: 'images/PuiPui1.png',
    location: 'New Delhi\, India',
    weightNumber: '1',
    weightUnit: 'kg',
    ownerName: 'Dev C Krishna',
    ownerImagePath: 'images/sejal.png',
    ownerCategory: 'Owner',
    ownerStatement: kPuiPuiText,
    photos: [
      'images/PuiPui1.png',
      'images/PuiPui2.png',
      'images/PuiPui3.png',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '12',
    name: 'Lemon',
    breedline1: 'Holland',
    breedline2: 'Lop',
    breed: 'Holland Lop',
    ageNumber: '5',
    ageUnit: 'years',
    gender: 'Male',
    image: 'images/lemon1.jpg',
    location: 'New Delhi\, India',
    weightNumber: '1.8',
    weightUnit: 'kg',
    ownerName: 'Armaan Malik',
    ownerImagePath: 'images/shaurya.png',
    ownerCategory: 'Owner',
    ownerStatement: kLemonText,
    photos: [
      'images/lemon1.jpg',
      'images/lemon2.png',
      'images/lemon3.png',
    ],
  ),
];

List<Animal> birds = [
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '13',
    name: 'Pipo',
    breedline1: 'Budge-',
    breedline2: 'rigar',
    breed: 'Budgerigar',
    ageNumber: '1',
    ageUnit: 'year',
    gender: 'Male',
    image: 'images/pipo1.jpeg',
    location: 'New Delhi\, India',
    weightNumber: '40',
    weightUnit: 'gm',
    ownerName: 'Red Paws Rescue',
    ownerImagePath: 'images/shelter2.jpg',
    ownerCategory: 'Shelter',
    ownerStatement: kPipoText,
    photos: [
      'images/pipo1.jpeg',
      'images/pipo2.jpeg',
      'images/pipo3.jpeg',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '14',
    name: 'Hedwig',
    breedline1: 'Snowy',
    breedline2: 'Owl',
    breed: 'Snowy Owl',
    ageNumber: '2',
    ageUnit: 'years',
    gender: 'Female',
    image: 'images/hedwig1.jpg',
    location: '4 Privet Drive, Little Whinging, Surrey ',
    weightNumber: '2',
    weightUnit: 'kg',
    ownerName: 'Harry Potter',
    ownerImagePath: 'images/harry.png',
    ownerCategory: 'Owner',
    ownerStatement: kHedwigText,
    photos: [
      'images/hedwig1.jpg',
      'images/hedwig2.jpg',
      'images/hedwig3.jpg',
    ],
  ),
  Animal(
    email: "dev.c.krishna.12345@gmail.com",
    id: '15',
    name: 'Buba',
    breedline1: 'Parakeet',
    breedline2: '',
    breed: 'Parakeet',
    ageNumber: '2',
    ageUnit: 'years',
    gender: 'Male',
    image: 'images/buba1.png',
    location: 'New Delhi\, India',
    weightNumber: '75',
    weightUnit: 'gm',
    ownerName: 'Hayward Animal Shelter',
    ownerImagePath: 'images/shelter4.png',
    ownerCategory: 'Shelter',
    ownerStatement: kBubaText,
    photos: [
      'images/buba1.png',
      'images/buba2.png',
      'images/buba3.png',
    ],
  ),
];
List<Animal> allAnimals = dogs + cats + bunnies + birds;
